services:
  backend:
    volumes:
      - ./backend/src:/app/src
    command:
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --app-dir
      - src

  ui:
    volumes:
      - ./ui/index.html:/app/index.html
      - ./ui/vite.config.js:/app/vite.config.js
      - ./ui/src:/app/src
    command:
      - npm
      - run
      - dev
      - --
      - --host
      - 0.0.0.0
